language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
env:
  - TEST_RUN_SUDO=0
  - TEST_RUN_SUDO=1
sudo: required
script:
  - perl Build.PL && ./Build && ./Build test
  - prove -lr xt/author/
